theme: minima
title: Test Stat Computing Seminar Page
author: DK
email: dophos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome discription. Series of seminars to get your feet wet on topics in statistical computing you might want to go deeper.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
